//
// FileStorageAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class FileStorageAPI {
    /**
     Endpoint to store an image

     - parameter body: (body)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func addImage(body: Object, completion: @escaping ((_ data: Data?,_ error: Error?) -> Void)) {
        addImageWithRequestBuilder(body: body).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Endpoint to store an image
     - POST /image
     - 

     - examples: [{contentType=application/json, example=""}]
     - parameter body: (body)  

     - returns: RequestBuilder<Data> 
     */
    open class func addImageWithRequestBuilder(body: Object) -> RequestBuilder<Data> {
        let path = "/image"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Data>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
}
