//
// ChangeUserData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ChangeUserData: Codable {

    public var userId: Int64
    public var login: LoginUser?

    public init(userId: Int64, login: LoginUser? = nil) {
        self.userId = userId
        self.login = login
    }


}
