//
// CreateGame.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CreateGame: Codable {

    public var mainPlayerId: Int64?
    public var players: [Int64]?

    public init(mainPlayerId: Int64? = nil, players: [Int64]? = nil) {
        self.mainPlayerId = mainPlayerId
        self.players = players
    }


}
