//
// Game.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Game: Codable {

    public var _id: Int64?
    public var topic: String?
    public var players: Int64?
    public var mainPlayer: Int64?
    public var gameState: String?

    public init(_id: Int64? = nil, topic: String? = nil, players: Int64? = nil, mainPlayer: Int64? = nil, gameState: String? = nil) {
        self._id = _id
        self.topic = topic
        self.players = players
        self.mainPlayer = mainPlayer
        self.gameState = gameState
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case topic
        case players
        case mainPlayer
        case gameState
    }

}
