//
// LoginUser.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct LoginUser: Codable {

    public var login: String
    public var password: String

    public init(login: String, password: String) {
        self.login = login
        self.password = password
    }


}
