//
// User.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct User: Codable {

    public var _id: Int64?
    public var login: String
    public var winningCount: Int64?
    public var losesCount: Int64?
    public var avatarUrl: String?

    public init(_id: Int64? = nil, login: String, winningCount: Int64? = nil, losesCount: Int64? = nil, avatarUrl: String? = nil) {
        self._id = _id
        self.login = login
        self.winningCount = winningCount
        self.losesCount = losesCount
        self.avatarUrl = avatarUrl
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case login
        case winningCount
        case losesCount
        case avatarUrl
    }

}
